name: Deploy to Server

on:
  push:
    branches:
      - 5-git-actions-connetion

jobs:
  build-and-push-to-ncp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: vst.kr.ncr.ntruss.com
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vst.kr.ncr.ntruss.com/vst/clova-x-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ncp
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Login to NCP Container Registry..."
            echo "${{ secrets.NCP_SECRET_KEY }}" | docker login --username ${{ secrets.NCP_ACCESS_KEY }} --password-stdin vst.kr.ncr.ntruss.com
            
            echo "Pulling latest Docker image..."
            docker pull vst.kr.ncr.ntruss.com/vst/clova-x-server:latest
            
            echo "Stopping old container..."
            docker stop clova-x-server || true
            docker rm clova-x-server || true
            
            echo "Starting new container..."
            docker run -d -p 8000:8000 --name clova-x-server vst.kr.ncr.ntruss.com/vst/clova-x-server:latest
